baseurl: "" # the subpath of your site, e.g. /blog
url: "https://strategie-tracker.smart-village.solutions" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  chapters:
    output: true
    sort_by: order
    permalink: /kapitel/:name/
    layout: chapter

defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      title:
      section:
      statements:
      - summary:
        id:
        categories:
        status: "not_implemented"
        last_update:
        reports:
        - title:
          url:

# Build settings
markdown: kramdown

plugins:
  - jekyll-timeago

jekyll_timeago:
  depth: 1
  threshold: 0.05
  default_locale: 'de'
  available_locales:
    - 'de'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/
  - requirements.txt